import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E6E6EE', 
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingVertical: 10,
    backgroundColor: '#1E1F29', 
    paddingHorizontal: 16,
    height: 50,
    marginTop:28,
  },
  title: {
    color: 'white',
    fontSize: 20,
    marginLeft: 50,
  },
  sidebar: {
    position: 'absolute',
    marginTop:28,
    left: 0,
    width: 270,
    height: '100%',
    backgroundColor: '#C69DEC',
    paddingTop: 60,
    paddingHorizontal: 20,
    zIndex: 10,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: { width: 3, height: 0 },
    shadowRadius: 8,
  },
  sidebarToggle: {
    position: 'absolute',
    top: 20,
    right: 20,
  },
  userSection: {
    marginBottom: 30,
    alignItems: 'center',
    padding: 15,
    borderRadius: 10,
  },
  userFoto: {
    width: 100,
    height: 100,
    borderRadius: 40,
    marginBottom: 10,
  },
  userName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'black',
    marginBottom: 3,
  },
  userEmail: {
    fontSize: 15,
    color: '#6E6D70',
  },
  optionItem2: {
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderWidth:2,
    borderRadius:20,
    padding:15,
    paddingTop:3,
    paddingBottom:3,
    marginTop:10,
  },
  optionItem: {
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(68, 67, 67, 0.34)',
  },
  optionText: {
    fontSize: 16,
    color: 'black',
    fontWeight: '500',
  },
  botonCerrarSesion: {
    right: 10,
    flexDirection: "row",
    backgroundColor: "#9A20E0", 
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 25,
    alignSelf: 'center',
    alignItems:'center',
    marginTop:30,
    marginLeft:20,
  },
  textoCerrarSesion: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  imagenLogo: {
    width: 150,
    height: 150,
    resizeMode: 'contain',
    alignSelf: 'center',
    position: 'absolute',
    bottom: 30,
  },
    
  buscador: {
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E1F29', 
    marginBottom:15,

  },
  buscadorInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ccc',
    padding: 10,
    borderRadius: 5,
    backgroundColor: 'white',
  },
  buscadorButton: {
    backgroundColor: '#006CD1', 
    padding: 10,
    borderRadius: 5,
    marginLeft: 5,
  },
  buscadorButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  titulo: {
    color: 'black',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  proyectosContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap', 
    justifyContent: 'space-between', 
    paddingHorizontal: 10,
  },
  proyecto: {
    width: '48%',
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 10,
    marginVertical: 10,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 5,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    minHeight: 280, 
  },
  imagen: {
    width: '100%',
    height: 150,
    borderRadius: 5,
  },
  carrera: {
    fontSize: 12,
    color: '#777',
    marginTop: 5,
  },
  titulo: {
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 3,
    marginBottom:3,
  },
  titulo2: {
    fontSize: 20,
    fontWeight: 'bold',
    marginTop: 5,
    marginBottom:5,
    textAlign:'center'
  },
  grupo: {
    color: '#9A20E0', 
    fontSize: 14,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  Button: {
    backgroundColor: '#9A20E0', 
    paddingVertical: 10,
    paddingHorizontal: 15, 
    borderRadius: 5,
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
