import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E6E6EE', 
    paddingBottom: 30, 
  },
  backButton: {
    marginTop: 20,
    position: 'absolute',
    top: 20,
    left: 10,
    zIndex: 1,
  },
  scrollContainer: {
    padding: 20,
  },
  title: {
    fontSize: 26,
    fontWeight: '600',
    marginVertical: 20,
    textAlign: 'center',
    color: '#333', 
  },
  imagenProyecto: {
    width: '100%',
    height: 220,
    backgroundColor: '#D3D3D3',
    borderRadius: 10, 
    marginBottom: 20,
  },
  infoContainer: {
    backgroundColor: '#FFFFFF', 
    padding: 10,
    width: '100%',
    borderRadius: 10,
    marginBottom: 20,
    elevation: 5, 
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    borderLeftWidth: 7,
    borderLeftColor: 'blue',
  },
  infoContainer2: {
    backgroundColor: '#C7DBF5', 
    padding: 10,
    width: '100%',
    borderRadius: 10,
    marginBottom: 20,
    marginTop: 10,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    borderLeftWidth: 7,
    borderLeftColor: 'blue',
  },
  infoTexto: {
    fontSize: 15,
    color: '#333',
    backgroundColor: 'transparent',
    fontWeight: '400',
  },
  sectionText: {
    fontSize: 16,
    color: '#444',
    marginBottom: 10,
    width: '90%',
    backgroundColor: 'white', 
    borderWidth: 0,
    borderRadius: 10,
    padding: 15,
    textAlign: 'justify',
    lineHeight: 24, 
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#6DA1EE', 
    padding: 15,
    borderRadius: 10,
    width: '90%',
    alignSelf: 'center',
    marginTop: 10,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFF',
  },
  sectionContent: {
    backgroundColor: 'white', 
    borderRadius: 10,
    marginTop: 10,
    width: '90%',
    alignSelf: 'center',
    borderLeftWidth: 7,
    borderLeftColor: 'blue',
  },
  
  backButtonText: {
    fontSize: 16,
    color: '#333',
    fontWeight: '600',
  },
  toggleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F0F0F0', 
    width: '90%',
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  sectionToggle: {
    fontSize: 18,
    color: '#0096C7', 
  },
  sectionButton: {
    padding: 15,
    marginTop: 20,
    backgroundColor: '#0096C7', 
    borderRadius: 10,
    width: '90%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionButtonText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  seccionDocumentacion: {
  padding: 15,
  borderRadius: 10,
  marginBottom: 20,
  width: '100%',
},
textoInfo: {
  fontSize: 16,
  color: '#333',
  marginBottom: 15,
},
tituloTabla: {
  fontSize: 18,
  fontWeight: 'bold',
  marginVertical: 10,
  color: '#333',
  justifyContent:'center',
  alignSelf:'center',
},
tabla: {
  borderWidth: 1,
  borderColor: 'black',
  borderRadius: 5,
  marginBottom: 20,
},
filaEncabezado: {
  flexDirection: 'row',
  backgroundColor: '#B8D2F3',
  borderBottomWidth: 1,
  borderColor: 'black',
},
celdaEncabezado: {
  flex: 1,
  padding: 10,
  fontWeight: 'bold',
  textAlign: 'center',
  borderRightWidth: 1,
  borderColor: 'black',
},
fila: {
  flexDirection: 'row',
  borderBottomWidth: 1,
  borderColor: 'black',
},
celda: {
  flex: 1,
  padding: 10,
  textAlign: 'center',
  borderRightWidth: 1,
  borderColor: 'black',
},

footer: {
  position: 'absolute',
  bottom: 0,
  left: 0,
  right: 0,
  height: 70,
  backgroundColor: '#006CD1',
  flexDirection: 'row',
  justifyContent: 'space-around',
  alignItems: 'center',
  borderTopLeftRadius: 20,
  borderTopRightRadius: 20,
  elevation: 20,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: -2 },
  shadowOpacity: 0.1,
  shadowRadius: 5,
},
footerItem: {
  flex: 1,
  alignItems: 'center',
  justifyContent: 'center',
},
footerText: {
  color: "white",
  fontSize: 12,
  marginTop: 5,
},
  
});
